public class DayOfTheWeek {
    public Static void dayOfWeek(){
        String dayOfWeek = 'Friday';
        
            switch on dayOfWeek{
            when 'Friday'{
                System.debug('Friday Drinks');
                
            }
            when 'Saturday'{
                System.debug('Sports Game');
            }
            when 'Sunday'{
                System.debug('Family Day');
            }
            when else{
                System.debug('Exciting Work');
                
            } 
                
        }
        
        
    }

}